{{- if .Values.controller.webhooks.ca }}
{{ $ca := genCA "terraform-controller" 7300 }}
{{ $dn := printf "controller.%s.svc.cluster.local" .Release.Namespace }}
{{ $sn := printf "controller.%s.svc" .Release.Namespace }}
{{ $server := genSignedCert "" (list "127.0.0.1") (list "localhost" "controller" $sn $dn) 3650 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
  labels:
{{- include "terraform-controller.labels" . | nindent 4 }}
type: Opaque
data:
  ca.pem: {{ $ca.Cert | b64enc }}
  tls.pem: {{ $server.Cert | b64enc }}
  tls-key.pem: {{ $server.Key | b64enc }}
{{- end }}
