apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terraform-controller.fullname" . }}
  labels:
    {{- include "terraform-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "terraform-controller.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "terraform-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: terraform-controller
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.controller.webhooks.ca }}
      volumes:
        - name: ca
          secret:
            secretName: ca
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - --apiserver-port={{ .Values.controller.port }}
            - --enable-webhook-registration={{ .Values.controller.enableWebhookRegistration }}
            - --git-image={{ .Values.controller.images.git }}
            - --metrics-port={{ .Values.controller.metricsPort }}
            - --terraform-image={{ .Values.controller.images.terraform }}
            - --terraform-version={{ .Values.controller.terraformVersion }}
            {{- if .Values.controller.webhooks.enabled }}
            - --tls-ca={{ .Values.controller.webhooks.tlsAuthority }}
            - --tls-dir={{ .Values.controller.webhooks.tlsDir }}
            - --tls-cert={{ .Values.controller.webhooks.tlsCert }}
            - --tls-key={{ .Values.controller.webhooks.tlsKey }}
            - --webhooks-port={{ .Values.controller.webhooks.port }}
            {{- else }}
            - --disable-webhooks
            {{- end }}
            - --verbose=true
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.controller.metricsPort }}
            - name: apiserver
              containerPort: {{ .Values.controller.port }}
            - name: webhook
              containerPort: {{ .Values.controller.webhooks.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.controller.webhooks.ca }}
          volumeMounts:
            - name: ca
              readOnly: true
              mountPath: /certs
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
