---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-controller
{{- if .Values.rbac.createExecutorServiceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-executor
{{- end }}
