---
name: Publish Tagged Images

on:
  push:
    tags:
      - "v*"

jobs:
  e2e-aws:
    uses: appvia/terraform-controller/.github/workflows/e2e.yaml@master
    secrets: inherit
    with:
      cloud: aws

  e2e-azure:
    uses: appvia/terraform-controller/.github/workflows/e2e.yaml@master
    secrets: inherit
    with:
      cloud: azure

  release-tagged-images:
    needs:
      - e2e-aws
      - e2e-azure
    uses: appvia/terraform-controller/.github/workflows/publish-images.yaml@ghcr
    secrets: inherit
